In [1]:
import numpy as np

## 1

In [49]:
arr = np.ones((10,2,2))

arr

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

## 2

In [60]:
np_arr=np.arange(24)
print("After 3D:\n")
print(np_arr.reshape(2,2,6))
np_arr=np_arr**2
print("\nAfter Reshape to 2D:\n")
print(np_arr.reshape(3,8))


After 3D:

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]

After Reshape to 2D:

[[  0   1   4   9  16  25  36  49]
 [ 64  81 100 121 144 169 196 225]
 [256 289 324 361 400 441 484 529]]


## 3

In [34]:
lis=list(range(0,10000000))
np_lis=np.arange(0,1,0.0000001)
print("python:\n")
%time b=[x**2 for x in lis] 
print("numpy:\n")
%time c=[np_lis**2]


python:

CPU times: total: 3.23 s
Wall time: 3.63 s
numpy:

CPU times: total: 31.2 ms
Wall time: 33.3 ms


## 4

In [61]:
arr=np.ones((5,5))
print(arr)
arr.reshape(5,5)
arr[1:4,1:4]=0
arr

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Practice

In [5]:
import numpy as np

In [6]:
arr=np.arange(10,20,0.9)
print(arr)
type(arr)

[10.  10.9 11.8 12.7 13.6 14.5 15.4 16.3 17.2 18.1 19.  19.9]


numpy.ndarray

In [7]:
z = np.zeros(10)
print(z)


ones=np.ones(10)
print(ones)
type(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


numpy.ndarray

In [8]:
one_d=np.ones((2))
one_d

array([1., 1.])

In [9]:
two_d=np.ones((2,4))
two_d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
three_d=np.ones((3,2,2,6))
three_d

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]])

In [11]:
four_d=np.ones((4,3,2,6))
four_d

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]])

In [12]:
tup=(3,3,3,3)
arr=np.zeros(tup)
arr
#modifying values
arr[0,0,0,0]=11
arr[1,1,1,1]=22
arr[2,2,2,2]=33
arr[1][1][0][2]=99 #c++ style
arr[2,2,0,1]=88
arr

array([[[[11.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0., 99.],
         [ 0., 22.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0., 88.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0., 33.]]]])

In [13]:
arr=np.zeros((0,3,2,2))
print("dimension: (arr.ndim): \t",  arr.ndim) #total number of dimension spaces
print("shape: arr.shape(): \t", arr.shape) #how many things in how many dimensions


dimension: (arr.ndim): 	 4
shape: arr.shape(): 	 (0, 3, 2, 2)


In [14]:
c=np.empty((2,2,3,2))
for i in range(len(c)):
    print(c[i])
    print("\n\n")

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]



[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]





In [15]:
r=np.arange(8)
r.reshape(8,1)
r.reshape(4,2)
r.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
py_arr=[4]
print(py_arr)
py_arr=[4,2]
print(py_arr)
py_arr=[[4,2]]
print(py_arr)
py_arr=[[0,1],[2,3]]
print(py_arr)
py_arr=[[[0,1],[2,3],[1,2]]]
print(py_arr)
np_arr=np.array(py_arr)
print("\n\n np arr: ",np_arr)



[4]
[4, 2]
[[4, 2]]
[[0, 1], [2, 3]]
[[[0, 1], [2, 3], [1, 2]]]


 np arr:  [[[0 1]
  [2 3]
  [1 2]]]
