In [11]:
from pandas import DataFrame as df
import pandas as pd
import numpy as np

In [65]:
B=df({0:[0,4,8,12,16], 1:[1,5,9,12,17], 2:[2,6,10,14,18], 3: [3,7,11,15,19]},columns=None)
B.to_csv('B.csv')
B

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  12  14  15
4  16  17  18  19

In [68]:
chunks=pd.read_csv('B.csv',chunksize=5)
chunks

In [70]:
chunklist=[]

In [69]:
for chunk in chunks:
    chunklist.append(chunk)

In [71]:
b=chunklist[0]
b

IndexError: list index out of range

In [72]:
b.iloc[0,0]+b.iloc[1,2]+b.iloc[3,2]

AttributeError: 'str' object has no attribute 'iloc'

In [17]:
print(b)

Unnamed: 0


In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
import sklearn.linear_model as lm
import matplotlib.pyplot as plt
import numpy as np
import sklearn.preprocessing as sp

In [4]:
data=pd.read_csv('iris.csv')
data.head(5)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [27]:
Y_1.reshape(1,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [21]:
Y_1=encoder.fit_transform(Y)

In [28]:
data=pd.read_csv('iris.csv')
data.head(5)
X=np.c_[data.iloc[:,0:4]]
Y=data.iloc[:,4]
encoder=sp.LabelEncoder()
Y_1=encoder.fit_transform(Y).reshape(-1,1)
#encoder=sp.OneHotEncoder()
#Y_1=encoder.fit_transform(np.c_[data.iloc[:,4:5]]).toarray()
Y_1


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [6]:
data=pd.read_csv('iris.csv')
data.head(5)
X=np.c_[data.iloc[:,0:4]]
Y=data.iloc[:,4]
encoder=sp.LabelEncoder()
Y_1=encoder.fit_transform(Y).reshape(-1,1)
#encoder=sp.OneHotEncoder()
#Y_1=encoder.fit_transform(np.c_[data.iloc[:,4:5]]).toarray()
Y_1


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [1]:
import sklearn.linear_model as lm

In [8]:
train_x,test_x,train_y,test_y=train_test_split(X,Y_1)

In [31]:
model=lm.LogisticRegression()
model.fit(train_x,train_y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [32]:
pred_y=model.predict([[1,2,1,3]])

In [34]:
model=lm.LogisticRegression()
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
from sklearn.metrics import confusion_matrix
pred_y=model.predict(test_x)
conf_mx = confusion_matrix(test_y, pred_y)
conf_mx

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[ 6,  0,  0],
       [ 0, 19,  3],
       [ 0,  0, 10]], dtype=int64)

In [9]:
model=lm.LogisticRegression()
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
pred_y=model.predict(test_x)
conf_mx = confusion_matrix(test_y, pred_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

array([[44,  0,  0],
       [ 0, 27,  1],
       [ 0,  1, 39]], dtype=int64)

In [11]:
pred_y=model.predict([[1,2,31,2]])

In [12]:
pred_y

array([2])

In [37]:
import sklearn.svm as sv
import sklearn.metrics as sm
model=sv.SVC(kernel='rbf')
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
#print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
#y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(test_y, pred_y)
conf_mx

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[ 6,  0,  0],
       [ 0, 18,  4],
       [ 0,  0, 10]], dtype=int64)

In [ ]:
import sklearn.svm as sv
import sklearn.metrics as sm
model=sv.SVC(kernel='rbf')
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

In [ ]:
import sklearn.svm as sv
import sklearn.metrics as sm
model=sv.SVC(kernel='rbf')
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

In [ ]:
import sklearn.svm as sv
import sklearn.metrics as sm
model=sv.SVC(kernel='sigmoid')
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

In [ ]:
import sklearn.tree as tr
import sklearn.metrics as sm
model=tr.ExtraTreeClassifier()
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx